"""add cloned_from_token to circuits

Revision ID: 172849fe4e12
Revises: d10522f38e87
Create Date: 2026-07-16 01:28:44.675569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172849fe4e12'
down_revision: Union[str, None] = 'd10522f38e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('cloned_from_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circuits', 'cloned_from_token')
    # ### end Alembic commands ###
