"""add clone_count to circuits

Revision ID: d10522f38e87
Revises: 30000df559fd
Create Date: 2026-07-15 20:41:47.288885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10522f38e87'
down_revision: Union[str, None] = '30000df559fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('clone_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circuits', 'clone_count')
    # ### end Alembic commands ###
